package com.xiaobu.blog.mapper;

import com.xiaobu.blog.common.page.Pageable;
import com.xiaobu.blog.model.Log;
import com.xiaobu.blog.model.LogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogMapper {
    List<Log> _selectLogBuPageable(Pageable pageable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    long countByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    int deleteByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    List<Log> selectByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    Log selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    int updateByPrimaryKeySelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_log
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    int updateByPrimaryKey(Log record);
}