package com.xiaobu.blog.mapper;

import com.xiaobu.blog.model.Tag;
import com.xiaobu.blog.model.TagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagMapper {

    int _insertTagSelective(Tag tag);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    long countByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    int deleteByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    List<Tag> selectByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    Tag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") Tag record, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    int updateByExample(@Param("record") Tag record, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_tag
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    int updateByPrimaryKey(Tag record);


}