package com.xiaobu.blog.model;

public class AdminUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_admin.id
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_admin.nickname
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_admin.username
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_admin.password
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_admin.avatar
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_admin.id
     *
     * @return the value of sm_admin.id
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_admin.id
     *
     * @param id the value for sm_admin.id
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_admin.nickname
     *
     * @return the value of sm_admin.nickname
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_admin.nickname
     *
     * @param nickname the value for sm_admin.nickname
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_admin.username
     *
     * @return the value of sm_admin.username
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_admin.username
     *
     * @param username the value for sm_admin.username
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_admin.password
     *
     * @return the value of sm_admin.password
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_admin.password
     *
     * @param password the value for sm_admin.password
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_admin.avatar
     *
     * @return the value of sm_admin.avatar
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_admin.avatar
     *
     * @param avatar the value for sm_admin.avatar
     *
     * @mbg.generated Mon Mar 23 10:10:15 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
}