package com.xiaobu.blog.model;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_article.id
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_article.status
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_article.title
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_article.abstract_info
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private String abstractInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_article.reading
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private Long reading;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_article.create_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_article.update_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_article.content
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_article.id
     *
     * @return the value of sm_article.id
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_article.id
     *
     * @param id the value for sm_article.id
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_article.status
     *
     * @return the value of sm_article.status
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_article.status
     *
     * @param status the value for sm_article.status
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_article.title
     *
     * @return the value of sm_article.title
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_article.title
     *
     * @param title the value for sm_article.title
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_article.abstract_info
     *
     * @return the value of sm_article.abstract_info
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public String getAbstractInfo() {
        return abstractInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_article.abstract_info
     *
     * @param abstractInfo the value for sm_article.abstract_info
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setAbstractInfo(String abstractInfo) {
        this.abstractInfo = abstractInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_article.reading
     *
     * @return the value of sm_article.reading
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public Long getReading() {
        return reading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_article.reading
     *
     * @param reading the value for sm_article.reading
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setReading(Long reading) {
        this.reading = reading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_article.create_time
     *
     * @return the value of sm_article.create_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_article.create_time
     *
     * @param createTime the value for sm_article.create_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_article.update_time
     *
     * @return the value of sm_article.update_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_article.update_time
     *
     * @param updateTime the value for sm_article.update_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_article.content
     *
     * @return the value of sm_article.content
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_article.content
     *
     * @param content the value for sm_article.content
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }
}