package com.xiaobu.blog.model;

import java.util.Date;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_log.id
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_log.ip
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_log.msg
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_log.create_time
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_log.update_time
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_log.id
     *
     * @return the value of sm_log.id
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_log.id
     *
     * @param id the value for sm_log.id
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_log.ip
     *
     * @return the value of sm_log.ip
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_log.ip
     *
     * @param ip the value for sm_log.ip
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_log.msg
     *
     * @return the value of sm_log.msg
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_log.msg
     *
     * @param msg the value for sm_log.msg
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_log.create_time
     *
     * @return the value of sm_log.create_time
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_log.create_time
     *
     * @param createTime the value for sm_log.create_time
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_log.update_time
     *
     * @return the value of sm_log.update_time
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_log.update_time
     *
     * @param updateTime the value for sm_log.update_time
     *
     * @mbg.generated Sun Mar 29 16:09:46 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}