package com.xiaobu.blog.model;

import java.util.Date;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_tag.id
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_tag.name
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_tag.create_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_tag.update_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_tag.id
     *
     * @return the value of sm_tag.id
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_tag.id
     *
     * @param id the value for sm_tag.id
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_tag.name
     *
     * @return the value of sm_tag.name
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_tag.name
     *
     * @param name the value for sm_tag.name
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_tag.create_time
     *
     * @return the value of sm_tag.create_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_tag.create_time
     *
     * @param createTime the value for sm_tag.create_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_tag.update_time
     *
     * @return the value of sm_tag.update_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_tag.update_time
     *
     * @param updateTime the value for sm_tag.update_time
     *
     * @mbg.generated Wed Mar 18 13:37:33 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}